version: '3'
services:
  postgres:
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
  web:
    volumes:
      - "./:/code"
    ports:
      - "8000:8000"
  frontend:
    build:
      context: ./frontend
      dockerfile: ../docker/frontend/Dockerfile-dev
    volumes:
      - "./frontend:/usr/src/app"
    ports:
      - "8080:80"