version: '3'
services:
  postgres:
    image: postgres:11.6
  web:
    restart: always
    env_file: .env
    build:
      context: .
      dockerfile: docker/backend/Dockerfile
    command: >
      bash -c "dockerize -wait tcp://postgres:5432 &&
               python manage.py migrate &&
               python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./:/code
    depends_on:
      - postgres
  frontend:
    env_file: ./frontend/.env
    build:
      context: ./frontend
      dockerfile: ../docker/frontend/Dockerfile-dev

  nginx:
    env_file: .env
    image: nginx:1.19.8
    container_name: zxc-arena.nginx
    ports:
      - 9080:80
    depends_on:
      - web
      - frontend
    volumes:
      - ./docker/nginx/templates:/etc/nginx/templates
  documentation:
    restart: always
    build:
      context: .
      dockerfile: ./docker/backend/Dockerfile
    command: "mkdocs serve"
    volumes:
      - ./:/code
