version: '3'
services:
  postgres:
    image: postgres:11.6
    ports:
    - "5432:5432"
  web:
    restart: always
    env_file: .env
    build: ./
    command: >
      bash -c "dockerize -wait tcp://postgres:5432 &&
               python manage.py migrate &&
               python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./:/code
    ports:
      - "8000:8000"
    depends_on:
      - postgres
  documentation:
    restart: always
    build: ./
    command: "mkdocs serve"
    volumes:
      - ./:/code
    ports:
      - "8001:8001"
