site_name: proxy6-middleware
site_description: Intermediate layer between the buyer and proxy6.net for commission calculation
repo_url: https://github.com/MailfTrue/proxy6-middleware
site_dir: site
copyright: Copyright &copy; 2020, <a href="https://github.com/MailfTrue">MailfTrue</a>.
dev_addr: 0.0.0.0:8001

nav:
  - Home: 'index.md'
  - API:
    - Authentication: 'api/authentication.md'
    - Users: 'api/users.md'
