# Stage 1 - Build Vue.js App inside temporary Node container
FROM node:carbon-alpine as builder

WORKDIR /usr/src/app
COPY . ./
RUN npm install

# Set default value for VUE_APP_API_BASE_URL if not provided
ARG VUE_APP_API_BASE_URL
ENV VUE_APP_API_BASE_URL=${VUE_APP_API_BASE_URL}

RUN npm run-script build

# Stage 2 - Deploy with NGNIX
FROM nginx:1.15.2-alpine

COPY --from=builder /usr/src/app/dist /var/www
COPY nginx.conf /etc/nginx/nginx.conf

EXPOSE 80

ENTRYPOINT ["nginx","-g","daemon off;"]
