# Generated by Django 4.0.4 on 2022-05-16 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_token_options_alter_token_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='token',
            options={},
        ),
    ]
