# Generated by Django 4.0.4 on 2022-05-16 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proxy6', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProxy',
        ),
    ]
