# Generated by Django 5.2.4 on 2025-07-25 18:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_payment_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CryptoBotPayment',
            fields=[
                ('invoice_id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('hash', models.CharField(max_length=128)),
                ('currency_type', models.CharField(choices=[('fiat', 'Fiat'), ('crypto', 'Crypto')], max_length=16)),
                ('crypto_asset', models.CharField(blank=True, choices=[('USDT', 'Usdt')], max_length=16, null=True)),
                ('fiat_asset', models.CharField(blank=True, choices=[('RUB', 'Rub')], max_length=16, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=16)),
                ('status', models.CharField(choices=[('active', 'Active'), ('paid', 'Paid'), ('expired', 'Expired')], default='active', max_length=16)),
                ('invoice_raw_data', models.JSONField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
